version: "3"

services:
  ruby:
    container_name: "${PROJECT_NAME}_ruby"
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/webapp:cached
    depends_on:
      - db
  react:
    container_name: "${PROJECT_NAME}_react"
    image: node:lts-alpine
    working_dir: /home/my-project
    volumes:
      - ./front:/home/my-project
    ports:
      - "8000:3000"
    command: ["yarn", "start"]
  db:
    image: mariadb:latest
    volumes:
       - ./docker/db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: api-spreading
       MYSQL_USER: user
       MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - "9000:80"
    depends_on:
       - db
    environment:
      PMA_HOST: db

volumes:
  db_data:
